language: node_js
node_js:
  - "8"
  - "6"
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
before_script:
  - sleep 15

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule sync
    - until git submodule update --init --recursive; do find . -iregex '.*\.gitmodules$' -exec sed -i 's/git@github.com:/https:\/\/github.com\//' "{}" \; ; git submodule foreach --recursive 'git submodule sync'; done
