#!/usr/bin/env python

from __future__ import (
    division,
    unicode_literals,
    print_function,
    absolute_import
)

from collections import OrderedDict
import gitcmdutils.semver as semver
import json
import subprocess
import shlex
import argparse
import logging
import sys

def prompt(question):
    reply = str(raw_input(question + ' (y/n): ')).lower().strip()
    if reply[0] == 'y':
        return True
    if reply[0] == 'n':
        return False
    else:
        return prompt("Please enter 'y' or 'n'...")

def main():
    parser = \
        argparse.ArgumentParser(description='Check that commits are error free with respect to tags and package.json versions')
    
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='log debug output')
    parser.add_argument('-p', '--patch', action='store_true',
                        help='increment patch version')
    parser.add_argument('-m', '--minor', action='store_true',
                        help='increment minor version')
    parser.add_argument('-M', '--major', action='store_true',
                        help='increment major version')

    opts = parser.parse_args(sys.argv[1:])

    logging.basicConfig(level=logging.DEBUG if opts.verbose else logging.WARN)

    try:
        with open('package.json', 'r') as f:
            package_json = json.load(f, object_pairs_hook=OrderedDict)
            version = package_json['version']
       
        new_tag = ""
        if opts.patch:
            new_tag = semver.bump_patch(version) 
        if opts.minor:
            new_tag = semver.bump_minor(version)
        if opts.major:
            new_tag = semver.bump_major(version)

        with open('package.json', 'w') as f:
            package_json['version'] = new_tag
            json.dump(package_json, f, indent=4, sort_keys=False)
        
        with open('package.json', 'r') as f:
            print(json.dumps(package_json, indent=4, sort_keys=False))
       
        print("!!! Changing version from %s to %s !!!" % (version, new_tag))
        if prompt("Would you like to push this change?"):
            git_commit_command = "git commit -am \"Bump version\""
            git_tag_command = "git tag -a v%s -m v%s" % (new_tag, new_tag)
            git_push_command = "git push --tags origin master"

            print("Issuing git command: %s" % (git_commit_command))
            subprocess.call(shlex.split(git_commit_command))
            print("Issuing git command: %s" % (git_tag_command))
            subprocess.call(shlex.split(git_tag_command))
            print("Issuing git command: %s" % (git_push_command))
            subprocess.call(shlex.split(git_push_command))
        else:
            print("Aborting...")

    except Exception, e:
        logging.exception(e)
        return -1
    
    return 0


if __name__ == '__main__':
    sys.exit(main())

