#!/usr/bin/env python

from __future__ import (
    division,
    unicode_literals,
    print_function,
    absolute_import
)

import argparse
import urlparse
import requests
import logging
import json
import os
import sys

import gitcmdutils.semver as semver

def main():
    parser = \
        argparse.ArgumentParser(description='update carbon-io docs submodules')
    
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='log debug output')

    opts = parser.parse_args(sys.argv[1:])

    logging.basicConfig(level=logging.DEBUG if opts.verbose else logging.WARN)
    
    #print('{!r}'.format(opts))

    with open('../package.json') as package_json:
        package = json.load(package_json)

    with open('../.gitmodules') as git_modules:
        for line in git_modules:
            print(line)

    return 0


if __name__ == '__main__':
    sys.exit(main())

